name = "art-worker"
main = "src/worker.js"
compatibility_date = "2026-01-01"
compatibility_flags = ["nodejs_compat"]


# --- Ambiente Dev ---
[env.dev]
name = "art-worker-dev"
vars = { ENVIRONMENT = "dev" }

[[env.dev.d1_databases]]
binding = "DB"
database_name = "art-db-dev"
# Replace with output of: wrangler d1 create art-db-dev
database_id = "d4cbf7ca-26a9-481e-8589-5089c2e24fdd"

# --- Ambiente Production ---
[env.production]
name = "art-worker"
vars = { ENVIRONMENT = "production" }

[[env.production.d1_databases]]
binding = "DB"
database_name = "art-db"
# IMPORTANTE: Reemplaza este ID por el ID real de tu base de datos D1 en Cloudflare
database_id = "PON_AQUI_TU_NUEVO_DATABASE_ID"
