name = "art-worker"
main = "src/worker.js"
compatibility_date = "2026-01-01"
compatibility_flags = ["nodejs_compat"]

[version_metadata]
binding = "CF_VERSION_METADATA"

# --- Ambiente Dev ---
[env.dev]
name = "art-worker-dev"
compatibility_date = "2026-01-01"
compatibility_flags = ["nodejs_compat"]
vars = { ENVIRONMENT = "dev" }

[env.dev.vars]
ENVIRONMENT = "dev"
SENTRY_DSN = "https://cf9345c02dc98aedf4a89f0a77af979d@o4511377702387712.ingest.us.sentry.io/4511377742692352"

[env.dev.version_metadata]
binding = "CF_VERSION_METADATA"

[[env.dev.d1_databases]]
binding = "DB"
database_name = "art-db-dev"
# Replace with output of: wrangler d1 create art-db-dev
database_id = "d4cbf7ca-26a9-481e-8589-5089c2e24fdd"

# --- Ambiente Production ---
[env.production]
name = "art-worker"
compatibility_date = "2026-01-01"
compatibility_flags = ["nodejs_compat"]
vars = { ENVIRONMENT = "production" }

[env.production.vars]
ENVIRONMENT = "production"
SENTRY_DSN = "https://cf9345c02dc98aedf4a89f0a77af979d@o4511377702387712.ingest.us.sentry.io/4511377742692352"

[env.production.version_metadata]
binding = "CF_VERSION_METADATA"

[[env.production.d1_databases]]
binding = "DB"
database_name = "art-db"
database_id = "d4cbf7ca-26a9-481e-8589-5089c2e24fdd"
